### ISSUE TITLE
Error if no zone exists

### ISSUE THREAD

**Issue by discostur** [wiedi/mellorimon#5]
Hi,

i think there may be a bug if you don't have anything running on your smartos host:

<pre>
/opt/mellorimon/zones_cpu.js:83
                if(line.length != 2) return
                       ^
TypeError: Cannot read property 'length' of null
    at /opt/mellorimon/zones_cpu.js:83:10
    at Array.forEach (native)
    at parseZones (/opt/mellorimon/zones_cpu.js:81:28)
    at /opt/mellorimon/zones_cpu.js:121:16
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:468:12)
[ Nov 18 09:08:17 Stopping because service exited with an error. ]
[ Nov 18 09:08:17 Executing start method ("/opt/mellorimon/server.js"). ]
</pre>

I have no zone running, just installed smartos and deployed mellorimon.

Greets
Kilian

**Comment by wiedi** [comment]
Thanks for reporting this!

Should be fixed in 3cc2d539b8c9b85c8fc2862b2719ab2e02f149fd

Let me know if you run into anything else
